image: Visual Studio 2017

init:
  - git config --global core.eol
  - git config --global core.autocrlf

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore ./GroboContainer.sln --verbosity m

build_script:
  - cmd: dotnet build --configuration Release ./GroboContainer.sln

test_script:
  - cmd: dotnet test --no-build --configuration Release --filter TestCategory!=LongRunning ./GroboContainer.Tests/GroboContainer.Tests.csproj --logger "trx;LogFileName=test-results.trx"

after_test:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $url = "https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)";
      $wc.UploadFile($url, (Resolve-Path './GroboContainer.Tests/TestResults/test-results.trx'))
