image: Visual Studio 2017

init:
  - cmd: git config --global core.autocrlf false

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore ./GroboContainer.sln --verbosity m

build_script:
  - cmd: dotnet build --configuration Release ./GroboContainer.sln

test_script:
  - cmd: dotnet test --no-build --configuration Release --filter TestCategory!=LongRunning ./GroboContainer.Tests/GroboContainer.Tests.csproj
